variables:
    PROJECT_URL: 'https://easytasks.robingenz.de/'

build:
    image: node:10
    stage: build
    cache:
        paths:
            - node_modules/
    script:
        - node -v
        - npm -v
        - npm install --quiet
        - npm run build-prod
    artifacts:
        paths:
            - dist/

deploy:
    image: alpine
    before_script:
        - apk --no-cache add lftp ca-certificates openssh
    stage: deploy
    environment:
        name: production
        url: $PROJECT_URL
    only:
        - master
    dependencies:
        - build
    cache:
        policy: pull
        paths:
            - node_modules/
    script:
        - lftp -c "set ftp:ssl-allow no; open -u $FTP_USERNAME,$FTP_PASSWORD $FTP_HOST; mirror -Rev --transfer-all ./dist/easytasks/ ./ --ignore-time --parallel=10 --exclude-glob=.htaccess --exclude-glob=.git* --exclude=.git/"
